name: Deploy Astro Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile

      - run: pnpm run build

      # Agrega aquí otros pasos de despliegue si usas Netlify/Vercel
